### ISSUE TITLE
escape room je stale rendrovana v petrzalke ako turisticka atrakcia

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapDiSK#1]
v osm je to uz zmenene na escape room (predtym to asi bolo [attraction](https://groups.google.com/forum/#!searchin/osm_sk/escape$20room/osm_sk/5JrRUqeMvhk/29FE9tzVAQAJ))
https://www.openstreetmap.org/node/3960655666
http://www.freemap.sk/#p=48.12855|17.11083|16|C,m=C

**Comment by aceman444** [comment]
Ano, tile Petrzalky ma stale mtime 20160410 03:10:31 . Nieco asi nie je v poriadku.
Predpokladam, ze nie vsetci Disk klienit tento tile odmietaju (kvoli pamatovej narocnosti), tak odvtedy by ho uz niekto vyrenderoval.

**Comment by aceman444** [comment]
Vraj nazvy a podobne veci sa nerenderuju vzdy spolu s ostatnymi objektami, ale len raz za cas. Teraz prebieha velke prerenderovanie casti Slovenska kvoli opravenemu importu dat a tato cast Bratislavy uz vyzera byt zaktualizovana (escape roomy su prec).

**Comment by petervojtek** [comment]
potvrdzujem, ze uz to vyzera byt pre-renderovane.
