### ISSUE TITLE
Renderovať amenity=feeding_place

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/FreemapDiSK#17]
Renderovať amenity=feeding_place

**Comment by tjamecny** [comment]
A nejakú ikonku pre to vieš poskytnúť? (najlepšie v nejakom hnedom odtieni, ako je napr. poľovnícky posed) Lebo to je jediný problém, prečo sa krmelce nezobrazujú na mape. Na freemap.sk stačí kliknúť v ľavom hornom rohu na "Objekty", rozbaliť kategóriu "Turizmus, turistika" a posledná položka je "Krmelec" s počtom 475. Pre zobrazenie na mape kliknúť na "Zobraziť POI".

**Comment by zdila** [comment]
Môže byť?

[krmelec.svg.zip](https://github.com/FreemapSlovakia/FreemapDiSK/files/703970/krmelec.svg.zip)

**Comment by zdila** [comment]
Alternatíva 2:

[krmelec2.svg.zip](https://github.com/FreemapSlovakia/FreemapDiSK/files/703976/krmelec2.svg.zip)

**Comment by tjamecny** [comment]
Zvolil som prvú verziu, zdá sa mi výstižnejšia.
Ako to bude vyzerať na mape po pregenerovaní POI (ktoré plánujem spustiť čoskoro):
![krmelec_mapa](https://cloud.githubusercontent.com/assets/16599347/21957817/d94b1aae-da9f-11e6-9a7e-cf65b74707f1.png)

Odkaz na mapu: https://www.freemap.sk/?l=17910-e142

**Comment by zdila** [comment]
Ďakujem. Asi by som to zmenšil na cca polovicu (ako je originál velkosť v SVG) :-)

**Comment by tjamecny** [comment]
Pôvodne som zvolil 16x16px, keďže aj iné ikony (ale nie všetky) majú toľko. Po zmenšení na 10x10px to už vyzerá dobre:
![krmelec_mapa_10px](https://cloud.githubusercontent.com/assets/16599347/21962874/99fe7e1e-db2f-11e6-9704-9ad060353521.png)

**Comment by zdila** [comment]
Pekne. Ďakujem :-)

**Comment by aceman444** [comment]
Zdravim, je mozne rovnako renderovat aj amenity=game_feeding ? V podstate ako alias, identicky tag zatial. Tych je este viac ako feeding_place.

**Comment by zdila** [comment]
To by sa potom hodilo aj pre https://github.com/FreemapSlovakia/MapsforgeFreemapHikingStyle/issues/5

**Comment by seg-on** [comment]
A čo building=hayloft?
Videl som také a dokonca je ich aj nejakých 44 zapísaných.
[http://overpass-turbo.eu/s/lJg](http://overpass-turbo.eu/s/lJg)

**Comment by tjamecny** [comment]
Do budúcnosti poprosím, aby ste neotvárali už zatvorenú Issue, hlavne ak už bol aj príslušný Milestone tiež zavretý. Jediná výnimka je, ak Issue nefunguje podľa požiadaviek a zároveň Milestone ešte nie je uzavretý (t.j. zmeny boli vyložené na web a DiSK klienti aktualizovaní). Taktiež nie je dobré mixovať témy, aj keď sa zdajú príbuzné. Treba otvoriť novú Issue a tam referencovať príslušnú Issue, ktorá už bola uzatvorená.

V skratke:
- na game_feeding som vytvoril #27 
- hayloft vyzerá byť nejaký slovenský výmysel, existuje len na SK a aj to v drvivej väčšine na severe stredného SK (asi Mirov výtvor). Ak existuje nejaký dôvod, prečo práve hayloft a nie barn (ktorých je 175000 v OSM), tak poprosím otvoriť novú Issue a napísať ho tam :)
