### ISSUE TITLE
Renderovat natural=fell,scree,bare_rock v turistickej vrstve?

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#21]
V turistickej vrstve na freemap.sk by stalo za zvazenie renderovat natural=fell, natural=scree, natural=bare_rock. Najma tie posledne 2 mozu byt velmi tazko pristupne.

Ukazka pouzitia:
http://www.openstreetmap.org/#map=15/49.1547/20.0166

**Comment by tjamecny** [comment]
scree a bare_rock sa renderujú aj cez Mapnik, mohol by som prepoužiť ich pattern. Fell sa nerenderuje, aj keď nejaké návrhy sú na https://trac.openstreetmap.org/ticket/3033 (neviem sa rozhodnúť, ktorý je "najvhodnejší"). Prípadne sa môže renderovať aj úplne iným vzorom/farbou, stačí len špecifikovať.

**Comment by aceman444** [comment]
OSM Carto su zatial dost proti: https://github.com/gravitystorm/openstreetmap-carto/issues/545

OsmAnd fell renderuje, ma tam akysi vzor s trojuholnikmi.

Takze si musime vybrat nieco my. Nejaka farba medzi zelenou a hnedou by mohla byt OK (taka nezdrava horska trava). Alebo vzor s tymi farbami. Predstavujem si nieco taketo: http://freebigpictures.com/wp-content/uploads/2009/09/alpine-grassland.jpg

**Comment by tjamecny** [comment]
Pre fell skúsim dať na začiatok farbu #a19f4a, a prípadne ju trochu zosvetliť, ak bude moc tmavá. Pozrel som carto patterny pre rock a scree (https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/generating_patterns), ale sú príliš veľké. Viac ako pol megabajtu kvôli jednému patternu je overkill, keďže súčsný štýl pre z16 má iba 180kB a pre z12 51kB. Skúsim pohľadať iný SVG pattern.

**Comment by tjamecny** [comment]
Po mnohých hodinách trápenia s Inkscape a rôznymi nástrojmi na optimalizáciu som vytvoril patterny pre bare_rock (9kB) a scree (1kB). Fell som zosvetlil, bol príliš tmavý (ako som očakával). Náhľad z testovania (treba si zobraziť plnú veľkosť):
![bare_rock-fell-scree](https://cloud.githubusercontent.com/assets/16599347/22865266/911098b8-f160-11e6-8cb5-75309280077e.png)

Ak bude treba, môžem ešte upraviť farbičky, stačí mi poslať upravený screenshot.

**Comment by zdila** [comment]
Ešte poprosím renderovať heath aj na menších zoomoch ako 14.

**Comment by aceman444** [comment]
Ano to vyzera fajn.
