### ISSUE TITLE
Nerenderuje leisure=park v PN

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#22]
Myslím že už som to raz riešil. Dôvod bol rozdielnosť DiSK klientov. Teraz by ale už tento problém nemal byť. Kde je teda problém?
http://www.freemap.sk/#p=48.59323|17.84294|15|T
http://www.openstreetmap.org/#map=16/48.5922/17.8347

**Comment by tjamecny** [comment]
Pri čistení a optimalizácii štýlov nedopatrením vypadlo renderovacie pravidlo na leisure=park/garden/common/green. Zostávajúce playground/playing_fields/pitch/golf_course sa renderovali v poriadku.
Príklad:
![pn_park](https://cloud.githubusercontent.com/assets/16599347/22626044/845290e8-eba4-11e6-9f28-fecbcd883a8c.png)

Zmeny sa prejavia na mape po vynútení aktualizácie všetkých DiSK klientov, predbežne do konca februára.

**Comment by aceman444** [comment]
Co je prosim leisure=green? Take skoro ani nie je na taginfo.
Ma to pravidlo platit pre landuse=village_green ?

**Comment by tjamecny** [comment]
Poprosím neznásilňovať túto Issue na iné témy, v budúcnosti sa to nebude dať dohľadať :(
Netreba sa báť otvoriť novú Issue, napr. "Je leisure=green zastaralé?", alebo ak si si istý, tak bez otáznika ;)
Tagovanie leisure=green vyzerá byť zastaralé, asi sa medzičasom zmenilo. Tagovanie landuse=village_green je zapracované v štýloch.

Nesledujem moc wiki, a preto zmeny typu landuse<->natural, prípadne shop vs. amenity sa nezapracovávajú do štýlov okamžite. A pritom vymazávanie zbytočností pomôže nielen vylepšiť výkon renderovania, ale hlavne sprehľadní štýly, takže má zmysel nahlasovať aj takéto veci.
