### ISSUE TITLE
Strom

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#26]
Renderujú sa aj stromy ako body/body?

**Comment by tjamecny** [comment]
Aktuálne sa natural=tree a ani tree_row nerenderujú. Tento nápad tu už bol: [http://mantis.freemap.sk/view.php?id=83](url), ale bolo to nerozhodne: 1 hlas za, 1 proti. Keďže je už "vačšina" za, pridám podporu do DiSK štýlov.

Návrh:
- použiť rovnaký štýl ako OSM, t.j. zelený kruh a uprostred hnedá bodka. 
- renderovať iba na turistickej/cyklomape, na autoatlase to asi nemá význam, či?
- renderovať až od z16, na menších zoomoch je to asi zbytočné.

Ak sú iné návrhy, sem s nimi :)

**Comment by seg-on** [comment]
- hej, od z16, na menších zoomoch ta nemá zmysel.
- mne by sa páčil len zelený kruh, alebo zelený kruh so sýtejším zeleným lemom. tá hnedá bodka mi príde trochu mätúca.
- podľa mňa aj na autoatlase to má zmysel, ale nahodil by som to zatiaľ iba na turistickú a cyklo
- alej by mohla byť vytvorená nie čiarou ako je to na OSM ale ako keď sa dajú tromi blízko seba. taká húsenica (môžem spraviť nejaký vizuál ak by si nevedel niekto predstaviť :).

**Comment by seg-on** [comment]
Takto nejako http://segi.wz.cz/stromy.png
keď na to teraz pozerám tak asi bez lemu to je lepšie :)

**Comment by tjamecny** [comment]
Vďaka za návrhy, hlavne za "húsenicu", vyzerá o dosť lepšie ako tá rovná čiara na OSM.org. Tiež sa mi viac páči len zelený kruh bez lemu a aj bez tej hnedej bodky. A navyše sa to ľahšie implementuje a vyžaduje menej času na renderovanie. Nakoniec som to hodil aj na autoatlas aj na turistickú/cyklomapu na z16.

Takto sa zobrazuje tree_row (renderuje sa skôr ako cesty, aby ich neprekrýval):
![natural_tree_row](https://cloud.githubusercontent.com/assets/16599347/23340894/837470b0-fc3e-11e6-9130-1706646ffb27.png)

A takto tree (na cintoríne je osamotený strom, a vľavo nadol od názvu sú štyri stromy vedľa seba, preto tvoria "húsenicu"):
![natural_tree](https://cloud.githubusercontent.com/assets/16599347/23340887/6a41e44c-fc3e-11e6-9163-0595e5006a3c.png)

Pri ďalšej aktualizácii DiSK klientov (plánovaná na zajtra, možno pozajtra) sa toto bude postupne objavovať na mape.

**Comment by seg-on** [comment]
Paráda ľúbi sa mi to :)
