### ISSUE TITLE
Lúky a polia niesu renderované v Autoatlase

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#28]
Lúky a polia niesu renderované v Autoatlase
http://www.freemap.sk/#p=48.60451|17.81956|16|A,m=AY
http://www.freemap.sk/#p=48.60451|17.81956|16|A,m=TY
http://www.openstreetmap.org/way/413843976#map=17/48.60443/17.82185&layers=N

**Comment by tjamecny** [comment]
Tak to bolo navrhnuté, keďže na autoatlase je renderovanie týchto plôch zbytočné. Takisto sa nerozlišuje typ lesa, všetky lesné plochy sú renderované jednou farbou.
