### ISSUE TITLE
nerenderuje tertiary_link ?

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#3]
Na aktualnej mape Petrzalky sa nevykresluje napr. cesta
https://www.openstreetmap.org/way/4564638 . Je to tertiary_link, zobrazuju sa na nej len jednosmerne sipky, ale samotna cesta chyba. Takych usekov je tam viac, napr. dalej https://www.openstreetmap.org/way/4642464.

**Comment by aceman444** [comment]
Kupodivu, tieto cesty sa renderuju ok na zoome 17 a 18.

**Comment by tjamecny** [comment]
Zoomy 17 a 18 boli vyrenderovane len jednorazovo inou technologiou, nie su aktualne a ani nebudu aktualizovane. Planujem ich tiez renderovat pomocou DiSKu, ale obnasa to vela prace, preto to tak skoro nebude.

**Comment by aceman444** [comment]
Dakujem.
