### ISSUE TITLE
Zdvojené renderovanie názvov na diaľnici a rýchlostnej komunikácií

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#32]
Na dialniciach a rýchlostných komunikáciach som si všimol že sú názvy zdvojeno renderované.
V prípadoch kde som si to všimol je posun veľmi malí a vytvára "duchov" alebo dôjde k nečitateľnosti prekrývaných názvov.
http://www.freemap.sk/#p=48.29886|17.6873|14|T
http://www.freemap.sk/#p=48.6606|17.87046|14|T

**Comment by didoa** [comment]
to preto, lebo su dve cesty blizko vedla seba (pruhy tam, a pruhy spat, oddelene) a podla best practice, by mali mat rovnako vela bodov kazdy usek. Freemap e c napis pre obe cesty, v zakrivenych usekoch su dlzky usekov malinko rozdielne a tak matematika kresliaca opakujuce sa nazvy sposobi duchov.

Neviem, ake by na toto bolo riesenie, lebo Freemap renderer nevie o tom, ze blizko a paralelne uz kreslil tie popisky - na texty na ciarach nemame automat na riesenie viditelnosti ako pre popisy bodov (labels).

**Comment by seg-on** [comment]
jasne chápem. riešenie ak by bolo tak by bolo asi aj neúmerné prínosu.
