### ISSUE TITLE
Vypadnutý tile na z11 pri Michalovciach

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#33]
Jedna dlaždica v strede mapy má len reliéf
http://www.freemap.sk/#p=48.74814|21.72903|11|T

**Comment by zdila** [comment]
+ https://freemapslovakia.github.io/freemap-v3-react-dist/#/T/14/48.942911/20.434098

**Comment by seg-on** [comment]
tak chyba asi u mňa. vymazal som cach a už to ide.
aj keď aby to v dvoch prehliadačoch spravilo my je celkom záhadou.

**Comment by tjamecny** [comment]
Chyba nie je v tvojom prijímači :)

Prišla mi do mailu notifikácia o tejto Issue, a okolo jednej poobede som dal prerenderovať asi 6 bielych tiles na z11 + jeden na z12 (nahlásil Martin). Chvíľu to trvá, kým sa to spracuje na serveri, ale podstatné je, že už je všetko v poriadku. Vďaka za nahlásenie.

**Comment by seg-on** [comment]
aha :D
tak pridám ešte jeden na z9 ;D
https://freemapslovakia.github.io/freemap-v3-react-dist/#/T/9/48.755283/19.069519

**Comment by tjamecny** [comment]
Priznávam, že som kontroloval len tiles na z11 :(
Dal som prerenderovať aj z9/283/176. Na serveri je už menej ako 128 tiles vo fronte na distribúciu na tile-servery, takže kým sa niečo iné nedorenderuje, tak sa zmena neprejaví na mape. Prinajhoršom sa tak stane po začatí renderovania zajtra ráno.

**Comment by seg-on** [comment]
Pohoda :)
