### ISSUE TITLE
Renderovať historic=wayside_cross aj pre cyklomapu

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#36]
Všimol som si že na cyklomape nerenderuje historic=wayside_cross. Šlo by doplniť rovnako ako turisitckej alebo lyžiarskej mape?

**Comment by tjamecny** [comment]
Pridané v rámci ostatného výpočtu pozície POI. Ikonky budú na cyklomape pribúdať postupne podľa toho, ako sa budú robiť zmeny na mape. Náhľad už prerenderovanej oblasti:
![cyklo_wayside_cross](https://user-images.githubusercontent.com/16599347/34335866-920c1b44-e952-11e7-85f7-9eee64599deb.png)
