### ISSUE TITLE
Neakceptuje poziciu z URL

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/FreemapDiSK#45]
Ak si otvorim adresu http://next.freemap.sk/?map=13/48.92701/20.42230&layers=T tak nevidim poziciu urcenu v URL, ale poziciu kde som naposledy bol na mape.

Nechapem ako to robi, v browseri Firefox 53.0.2 (windows) nepomoze ani vycistenie cookies (po vycisteni a navsteve uz ani nevidim nove cookies), ani restart browsera.

**Comment by seg-on** [comment]
Vyzerá že to neni v prehliadači. U mňa to isté.

**Comment by zdila** [comment]
Zatvaram - netrafil si projekt. Toto patri do https://github.com/FreemapSlovakia/freemap-v3-react/issues.

PS: medzicasom opravene.
