### ISSUE TITLE
next nejde v IE

### ISSUE THREAD

**Issue by miro-janosik** [FreemapSlovakia/FreemapDiSK#46]
V prehliadaci Internet Explorer 11.0.9600 sa mi nezobrazi next.freemap.sk, vidim iba prazdnu stranku. Zdrojak stranky:

<!DOCTYPE html>
<html>

  <head>
    <title>Freemap</title>

    <meta charset="UTF-8">
    <meta name="description" content="Freemap Slovakia Map Portal">
    <meta name="keywords" content="map, freemap">
    <meta name="author" content="Freemap Slovakia">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>

    <link rel="stylesheet" href="//unpkg.com/leaflet@1.0.3/dist/leaflet.css"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
  </head>

  <body>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-89861822-3', 'auto');
      ga('send', 'pageview');
    </script>

    <div id="app"></div>
    <script src="index.js"></script>
  </body>

</html>

www.freemap.sk funguje (po chvili sa zobrazi), platforma Windows 8.

**Comment by zdila** [comment]
a co vravi JS konzola?

**Comment by zdila** [comment]
Zatvaram - netrafil si projekt. Toto patri do https://github.com/FreemapSlovakia/freemap-v3-react/issues.

PS: medzicasom opravene.

**Comment by miro-janosik** [comment]
Ah, takto by sa na bugy odpovedat nemalo.
Siel som sem cez link "nahlasit chybu" (treba opravit wiki http://wiki.freemap.sk/NahlasenieChyby )

**Comment by zdila** [comment]
nemalo, ale developeri su casto arogantni :-D

**Comment by tjamecny** [comment]
> Ah, takto by sa na bugy odpovedat nemalo.

Tiez si myslim, ze taketo odpalkovanie nie je uplne v poriadku. Nemame tych hlaseni 100 za den, preto by nemal byt problem skopirovat text Issue do spravneho projektu, a uzavriet s tym, ze sa uzivatelovi oznami, kde sa nachadza nova Issue (cez crosslink).

Wiki je v poriadku, hned prva veta zacina "Ak ste našli chybu na mape...", a tu sa o taku chybu nejedna. Ale bude pre uzivatela jednoznacnejsie, ked sa stranka rozsiri aj o sekciu "vyvojova verzia portalu", ze chyby s funkcnostou patria tam.

**Comment by zdila** [comment]
Nerozumiem, načo by som mal tú issue kopírovať, keď som písal že "medzičasom fixnuté"?

A keby aj nie, nemusím mať dobrú vôľu aby som kopíroval issue na správne miesto. Autor dostal notifikáciu a má to spraviť sám aby sa to naučil. V mojom prípade sa naučím veci oveľa skôr ak som nútený ich spraviť sám a nespraví ich niekto za mňa. Napríklad mirecnet nemal vôbec problém to spraviť bez nejakého urazenia sa, dokonca sa ešte ospravedlnil.

**Comment by miro-janosik** [comment]
Ja to viem spraviť aj sám, som programátor. Ale pred časom sme mali
diskusiu o tom, že bežný užívateľ si ledva horko-ťažko spraví github účet.
A ak dostane toto ako reakciu, tak sa na to asi po tých starostiach vykašle
reportovať ďalšie bugy...
  Miro

Dňa 19. mája 2017, 21:52, Martin Ždila <notifications@github.com>
napísal(-a):
