### ISSUE TITLE
 lezecke lokality sa oznacuju ako strom

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#48]
Zdravim,
vsimol som si, ze v GPS Garmin sa moje lezecke lokality popod skaly oznacuju ako strom.

sport=climbing

V GPS sa zobrazuje strom.
Pozrite sa na to pls.
Dakujem

**Comment by tjamecny** [comment]
Prekopíroval som do https://github.com/FreemapSlovakia/freemapSKtopo/issues/1 , keďže sa to netýka priamo mapy na webe, ale Garmin-u.
