### ISSUE TITLE
Zla dlazdica mapy pri Tlmacoch.

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#49]
Zla dlazdica mapy pri Tlmacoch.

http://next.freemap.sk/?map=13/48.26354/18.50381&layers=T

Pozrite sa prosim na to. 
Dakujem

**Comment by tjamecny** [comment]
Pravdepodobne mal niekto zle nakonfigurovaného DiSK klienta, asi viac klientov malo rovnaký pracovný adresár.

Dal som prerenderovať, už to vyzerá v poriadku. Vďaka za nahlásenie.
