### ISSUE TITLE
Problem renderovania - v Ilanovskej doline na Krakovu holu

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#53]
Cez vikend som zmapoval lesny chodnik v Ilanoveskej doline az na Krakovu holu v dlzke 8 km. 
https://www.openstreetmap.org/way/529261601

Nic sa vsak dnes na Freemape neobjavilo. http://next.freemap.sk/?map=15/49.02011/19.61156&layers=Tt

Asi daka chyba. Skuste pozriet. Nahrate: 2017-10-01 T20:13:53Z

**Comment by tjamecny** [comment]
Chodník je viditeľný na freemap-e. Pravdepodobne sa renderoval až večer, keďže včera sa renderovalo o dosť viac tiles, ako po iné dni.
