### ISSUE TITLE
Chybny stvorec na Freemape

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#55]
Chybny stvorec na Freemape
http://next.freemap.sk/?map=13/49.29468/20.87737&layers=T
http://next.freemap.sk/?map=14/49.29726/20.87750&layers=T

Pozrite sa prosim na to.

**Comment by Mirecnet** [comment]
Dalsi stvorec
http://next.freemap.sk/?map=15/49.20176/20.17873&layers=T

**Comment by tjamecny** [comment]
Vďaka za report.

Tile pri obci Orlov pochádza z 18.9., t.j. jedná sa o rovnaký problém, ktorý sa riešil aj na fóre. Dal som prerenderovať.
Druhý tile vo Vysokých Tatrách je len zle poskladaný (podklady sú na serveri správne), vynútil som jeho znovuposkladanie. Večer skontrolujem výsledky a zavriem túto issue.

**Comment by tjamecny** [comment]
Problémové tiles sa už zobrazujú korektne, zatváram.

**Comment by Mirecnet** [comment]
jj..dik uz za vyriesenie problemu
