### ISSUE TITLE
niekedy sa nevykresli makcen na ď

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#56]
Na obrazku http://next.freemap.sk/?map=17/48.27911/17.75178&layers=C, chyba makcen v nazve Šintava, mokraď (node 5151988025). V nazve mesta Sereď (hned zapadne) vsak nechyba.

**Comment by aceman444** [comment]
Aha, moze to byt, ze nie je aktualizovana vrstva s nazvami, takze sa len zobrazuje stav z doby nez som ten makcen pridal v OSM datach?

**Comment by tjamecny** [comment]
Informáciu o spustení výpočtu pozície POI a názvov som poslal na fórum 16.10. o 10:34. To znamená, že vo výpočte boli zahrnuté všetky zmeny, ktoré boli nahraté do OSM do 15.10. 23:59. TIM http://www.openstreetmap.org/node/5151988025 bol upravený až 17.10. a teda táto zmena sa prejaví pri ďalšom výpočte, ktorý neplánujem skôr, ako v polovici Novembra.

**Comment by aceman444** [comment]
V pohode, zabudol som, ze nazvy sa nerenderuju denne. Dakujem.

**Comment by aceman444** [comment]
Label mozete dat aj "invalid", kedze som myslel, ze je to renderovacia chyba :)
