### ISSUE TITLE
Nekompletne vyrenderovana turisticka trasa

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/FreemapDiSK#57]
TZT https://www.openstreetmap.org/relation/1692127 je nekompletne vyrenderovana, hoci posledne bola menena az cca pred rokom.

Hlasim to ako bug pretoze takychto tras moze byt kvoli niecomu postihnutych viacero.

![image](https://user-images.githubusercontent.com/636095/32095275-e777de52-bb02-11e7-9dbe-dee202799ebf.png)

**Comment by tjamecny** [comment]
Chybaju nam data v TRAPI: http://dev.freemap.sk/trapi/api/0.6/map/relation/1692127
Urcite by sa to opravilo reimportom celeho SK, ale je to casovo narocne a je dobre za tym pustit aj POI & labels placement, co je dalsia casovo narocna uloha. Preto by som tuto moznost odlozil aspon o nejaky ten mesiac.
Skusim upravit dennu aktulizaciu tak, aby zahrnula aj tuto relaciu (v DB ju stale mame) a dam vediet, ci to zabralo. V pripade pozitivneho vysledku potom skontrolujem aspon TZT/CZT trasy, ci su vsetky v TRAPI.

**Comment by zdila** [comment]
Znacku uz vidno.
