### ISSUE TITLE
uloženie posledných dát v bigslovakia.pbf

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/FreemapDiSK#58]
niekam uložiť ktoré sú posledné dáta v bigslovakia, aby bolo jasné či niektoré nové údaje sú už v databáze.

**Comment by tjamecny** [comment]
Duplicita #35

**Comment by MichalPP** [comment]
nie je to duplicita, sú to dve rôzne veci.

**Comment by didoa** [comment]
time stamp suboru nie je dost ?

**Comment by MichalPP** [comment]
to je dátum vytvorenia súbor a nie dátum dokedy sú tam dáta (to spracovanie asi trvá).

**Comment by tjamecny** [comment]
@MichalPP keď bude zverejnený napr. bigslovakia171107.pbf, čo znamená, že obsahuje OSM dáta do 6.11.2017 23:59, bude ti to stačiť? A zároveň to vyrieši aj #35 .

**Comment by didoa** [comment]
pouziva sa daily diff... takze je to takmer vzdy ten isty cas kazdy den, okrem pripadov, ked sa im nieco posere a urobia to neskor ... ako pisal @tjamecny ti musi stacit... :)

**Comment by MichalPP** [comment]
#35 je o tom, aby klient nemusel tipovať aký je dnes dátum, ale iba stiahol dáta wgetom.

takže môžem brať že posledné dáta sú `round(timestamp) - 1 day`

**Comment by MichalPP** [comment]
vďaka za snahu, vyriešil som inak.
