### ISSUE TITLE
nespravne prerenderovana cyklorelacia

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#61]
Na http://next.freemap.sk/?map=16/48.282957/17.756245&layers=C je vidiet nezaktualizovanu dlazdicu, cast cyklotrasy 2207 je vidiet este na ceste Nitranska, kde uz davno v datach nie je.
Tato oblast sa nespravne zaktualizovala druhykrat, co moze byt vo veci?

**Comment by tjamecny** [comment]
Tile 12/2250/1418 bol naposledy renderovaný 10.10.2017 a predpokladám, že si z cesty Nitrianska odstránil cykloreláciu až po tomto dátume. Nejak nezafungovala detekcia zmenených tiles (asi preto, že tam žiadna iná zmena nebola), takže som dal manuálne prerenderovať daný tile, a už je to v poriadku.

**Comment by aceman444** [comment]
A netreba teda opravit detekciu zmenenych tiles? :) Ano ziadna ina zmena tam asi nebola. Zle sa prekreslili aj ine dlazdice, ale odvtedy som urobil dalsie zmeny a tie ine sa prekreslili znovu a uz su dobre.

**Comment by tjamecny** [comment]
Opraviť toho treba omnoho viac :(
