### ISSUE TITLE
Chybajuca nadmorska vyska vrcholov na Freemape

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#62]
Chybajuca nadmorska vyska vrcholov na Freemape (turisticka mapa)

Chcem len pripomenut nahlasenu chybu:
po poslednom renderingu Freemapu zmizla pod nazvom vrcholu aj nadmorska vyska

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/osm_sk/gfqreS0aSnc/eHljnpceBgAJ

**Comment by tjamecny** [comment]
Myslím na to. Rovnako zmizla nadmorská výška aj na TIM.

**Comment by seg-on** [comment]
Čo je TIM?

**Comment by tjamecny** [comment]
Turistické informačné miesto. Viac na [webe KST](http://www.kst.sk/index.php?option=com_content&task=view&id=131&Itemid=87)

**Comment by seg-on** [comment]
díki za dovzdelanie :D

**Comment by tjamecny** [comment]
Po poslednom výpočte pozície POI & názvov a následnom prerenderovaní dlaždíc s názvami, je problém odstránený.
