### ISSUE TITLE
Chybajuci les medzi Sipkovym a Visnovym

### ISSUE THREAD

**Issue by petervojtek** [FreemapSlovakia/FreemapDiSK#63]
nemal som zatial cas skumat osm data, ci to len nahodou niekto nezmazal.
https://www.freemap.sk/?map=12/48.691527/17.746010&layers=C

<img width="527" alt="screenshot 2017-11-29 07 28 58" src="https://user-images.githubusercontent.com/225506/33361186-57eca12a-d4d7-11e7-9c2c-e16fc0d1dc72.png">

**Comment by tjamecny** [comment]
Problém sa už riešil na diskusnom fóre: [https://groups.google.com/d/msg/osm_sk/FhAAWFiIs7c/Lf9webBEBgAJ](url), ale dané územie sa odvtedy ešte nerederovalo kompletne, tak som dal chýbajúce dlaždice manuálne prerenderovať. Po kontrole zavriem túto issue.

**Comment by tjamecny** [comment]
Mapa je v poriadku, zatváram.
