### ISSUE TITLE
Chybne renderovany svetly stvorec v Rackovej a Jamnickej doline - Zapadne Tatry

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#64]
Chybne renderovany svetly stvorec  v Rackovej a Jamnickej doline - Zapadne Tatry
(100m)
https://www.freemap.sk/?map=16/49.150008/19.781345&layers=Ts
(300m)
https://www.freemap.sk/?map=15/49.148815/19.789703&layers=Ts

Zrejme daka chyba. Pozrite sa na to prosim.

**Comment by seg-on** [comment]
Ahoj,
toto sa už rieši. je potrebné prerenderovať dlaždice reliéfu.
https://github.com/FreemapSlovakia/FreemapDiSK/issues/54

**Comment by Mirecnet** [comment]
Naviem v ako je to stadiu riesenia, ale je to tam stale.
Hlasil som na osm_sk-googlegroups. Pre istotu hlasim aj sem.,

Nasiel som este jeden biely stvorec na Magure v Tichej a Koprovej doline v Zapadnych Tatrach.

https://www.freemap.sk/?map=15/49.204953/19.968832&layers=T

**Comment by tjamecny** [comment]
Prosím nemixuj rôzne problémy dokopy. Biely štvorec bol zapríčinený zlým poskladaním tile na serveri a svetlejší odtieň je spôsobený staršími dlaždicami. Kým sa neujednotí názor, ktoré dlaždice s reliéfom sa použijú, tak sa s týmto problémom nepohneme ďalej.

Radšej preventívne zatváram túto Issue skôr, ako sem pribudne ešte niečo ďalšie... pôvodne nahlásený problém bude vyriešený v rámci #54, ako už napísal @seg-on.
