### ISSUE TITLE
Neexistujuca banska stolna, ktora nieje zakreslena v OSM....

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#67]
Nasiel som zaujimavu chybu v masive Sipruna vo Velkej Fatre. Nachadza sa v Freemap uz asi od leta. Ide o neexistujucu bansku stolnu, ktora nieje zakreslena v OSM.
 Ked si ju nacitam cez JOSM, tak tam nieje. Najlepsie je, ak si dam cez Freemap vyhladat MIESTA -"stolna" v tejto oblasti, tak oznaci dalsie neexistujuce miesto asi 300 m severne.
Viac na tomto obrazku:
![neexistujuca-bana-siprun](https://user-images.githubusercontent.com/24828961/34708382-b44d577e-f512-11e7-89a2-f09f6ee35650.jpg)

https://www.freemap.sk/?map=16/49.010374/19.254152&layers=T

Jedna sa zrejme o chybu. Prosim, pozrite sa na to.
Dakujem.

**Comment by tjamecny** [comment]
Máš pravdu a aj nemáš pravdu :)
Tá štôlňa existuje, akurát je zakreslená ako [cesta](https://www.openstreetmap.org/way/328863846), a potom záleží na spôsobe spracovania dát, kde sa vykreslí ikona:
1) freemap zjavne berie do úvahy všetky body tejto cesty, preto je ikonka umiestnená v dlaždici južnejšie
2) overpass-api, odkiaľ sa načítavajú POI, asi priemeruje len počiatočný a koncový bod, a preto je marker umiestnený severnejšie.

Pravdu máš v tom, že sa jedná o bug - v OSM dátach. Keď z tohto potoka odstrániš tag štôlne, tak na freemape sa to prejaví pri ďalšom výpočte POI, a na overpass-api takmer okamžite.

**Comment by tjamecny** [comment]
Link na osm_sk diskusiu, ale bez nejakého záveru: [https://groups.google.com/forum/#!msg/osm_sk/g4MXVWTiOPc/XZdHdFueBwAJ](url)

**Comment by Mirecnet** [comment]
Preklikal a prehaladal som vsetko naokolo, ale ten potok ma nenapadlo pozriet.
Je to opravene.
Dik za to, ze si sa na to pozrel.
