### ISSUE TITLE
Chybne renderovany stvorec pri Ilave

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#68]
Zdravim,
nasiel som chybne renderovany stvorec v mape pri Ilave

https://www.freemap.sk/?map=13/49.010852/18.336611&layers=T

Prosim pozrite sa na to.

**Comment by tjamecny** [comment]
Poslal som mail majiteľovi daného DiSK klienta, nech si preverí konfiguráciu. Po prerenderovaní mojím DiSK klientom je to už v poriadku (chýba ešte rozdistribuovať zopár tiles na z16 na tileservery, do rána by to malo byť aj tam OK).

Vďaka za report.

**Comment by Mirecnet** [comment]
Aj tebe velka vdaka, ze tam promtne a rychlo riesis najdene chyby.
