### ISSUE TITLE
nekompletne nazvy niektorych objektov

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#7]
Niektore nazvy objektov su nekompletne.
A nebude to tym, ze by tam nebolo miesto, alebo ze by bol napis na zlome dlazdic.

Nazov kanala (ma byt Chorvatske rameno):
http://d.freemap.sk/A/16/35883/22747.png
http://a.freemap.sk/A/16/35882/22750.png

Cislo linky MHD (ma byt N8 -> N80 a 9 -> 9x):
http://t1.freemap.sk/data/layers/transport/16/35886/22747.png

**Comment by tjamecny** [comment]
Renderovanie názvov potokov a riek bolo opravené už dávnejšie, a mierne doladené v #10 . Teraz bolo opravené zobrazovanie čísiel liniek MHD + pridané biele pozadie pod názvami zastávok pre lepšiu čitateľnosť:
![mhd_linky](https://cloud.githubusercontent.com/assets/16599347/21582983/59baa2b0-d06c-11e6-8097-6c67765a6990.png)

Zmeny sa na mape prejavia po ďalšej aktualizácii DiSKu.

**Comment by aceman444** [comment]
Dakujem. Na Vasom obrazku vyzeraju linky OK, ale priamo na zdrojovom obrazku http://t1.freemap.sk/data/layers/transport/16/35886/22747.png su stale linky "N", "N8" a "9".

**Comment by tjamecny** [comment]
Ako je napísané pod obrázkom v https://github.com/FreemapSlovakia/FreemapDiSK/issues/7#issuecomment-269919126 , zmeny sa prejavia až bude vynútená aktualizácia všetkých bežiacich DiSK klientov, čo sa zatiaľ nestalo. Plánujem to spraviť v priebehu budúceho týždňa, spolu s reimportom OSM dát do Freemap DB.

**Comment by aceman444** [comment]
A preco je to teda na Vasom obrazku dobre? To je nejaka testovacia lokalna verzia?
