### ISSUE TITLE
Renderuje sa modrá značka, ktorá nie je v OSM dátach

### ISSUE THREAD

**Issue by pdragun** [FreemapSlovakia/FreemapDiSK#71]
Zdar,
v hornom úseku medzi bodmi: https://www.freemap.sk/?map=16/48.732580/18.966962&layers=T&tool=info-point&info-point=48.728497/18.951695&info-point=48.738630/18.978560
sa renderuje nejaká modrá značka, ktorú nevidím v OSM dátach. Ten chodník má relácie: červená, E8 (červená), Cesta SNP (červená) a zelená cyklo. Myslím, že daným úsekom ani žiadna modrá v skutočnosti neprechádza.

(Dvojitá červená je tam "správne", ale čoskoro by už mala byť len jedna: https://groups.google.com/forum/#!topic/osm_sk/QYIslunBSFk)

Vďaka,
Peter ml.

**Comment by zdila** [comment]
Ten usek je v "modrej" relacii https://www.openstreetmap.org/relation/1175728#map=14/48.7277/18.9682 takze chyba nie je v rendererri.

**Comment by pdragun** [comment]
Áno, chyba bola na mojej strane. Ospravedlňujem sa.
Zmiatla ma modrá farba pri E8, ktorá je na našom území červená. Je tam použitá chybná relácia: https://groups.google.com/forum/#!msg/osm_sk/QYIslunBSFk/pUABzGOiCQAJ
