### ISSUE TITLE
Chybné vykreslenie výškovej mapy 

### ISSUE THREAD

**Issue by adamzivcak** [FreemapSlovakia/FreemapDiSK#76]
Pri pokuse o vykreslenie výškovej mapy na trase Popradské pleso - Rysy, sa na niektorých miestach vyresľujú miesta s nezmyselnou nadmorskou výškou ( -32 768m.n.m).  Prikladám odkaz s naplánovanou trasou, kde sa mi to takto vykresľuje: https://www.freemap.sk/?map=15/49.168784/20.065713&layers=T&tool=route-planner&points=49.156029/20.076184,49.179347/20.087986&transport=foot.  Predpokladám že niekde dochádza k pretečeniu, nakoľko -32768 je hodnota int_min-1.

**Comment by didoa** [comment]
Zdravim, nie je to pretecenie, skor SRTM data, ktore nie su void-filled - obsahuju miesta kde nie su vyskove data. su dve moznosti:
1) voids sa doplnia interpolacne
2) upravi sa kod, aby vynechaval hodnotu -32768 z vyskovych dat

**Comment by zdila** [comment]
Problem sa odstranil nedavnym nasadenim noveho elevation API.
