### ISSUE TITLE
Zle vykreslovanie ceskych map

### ISSUE THREAD

**Issue by KONIKPK** [FreemapSlovakia/FreemapDiSK#77]
Pri prezerani map CZ sa pri hocijakom zoome ukazuju len stvorce.
![image](https://user-images.githubusercontent.com/10882733/44655159-71bb1300-a9f4-11e8-959e-c0f6e3b9e678.png)

**Comment by zdila** [comment]
Freemap specificke mapy (auto, turistika, cyklistika) renderujeme iba v sirsom okoli Slovenska, dalej zatial nie. Tam sa zatial renderuje takyto "neporiadok", ktory chceme odstranit (vid. #34). Je to pozostatok povodneho renderovania kde sa mimo slovneska pouzival podklad z www.osm.org.
