### ISSUE TITLE
Výpadok tieňovania

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/FreemapDiSK#78]
Vyzerá to že novoprerenderované dlaždice nemajú tieňovanie.
![image](https://user-images.githubusercontent.com/19683952/45739324-fdd6e980-bbf2-11e8-8f30-2e882d8607b7.png)
https://www.freemap.sk/?map=12/48.673053/17.986336&layers=Ct1

**Comment by zdila** [comment]
Ja ho vidim, ale je fest jemne.

**Comment by tjamecny** [comment]
@kaylesk Mohol by si spraviť reliéf tmavší, podľa možnosti rovnaký, [ako je na z14](https://www.freemap.sk/?map=14/48.905944/20.830765&layers=T) (vľavo) ? A s rovnakými parametrami ho vygenerovať aj pre z15/z16, keďže ten [aktuálny na freemap-e](https://www.freemap.sk/?map=15/48.904660/20.827847&layers=T) je už príliš tmavý.

**Comment by kaylesk** [comment]
Našiel som nejaké hodnoty pre reliéf, tak som skúsil malú časť Z14-Z16 vygenerovať. Len sa mi to zdá nejaké bledšie a hlavne nesedí mi to s tím čo vidím na mape :( viď http://tiles.kayle.sk/relief.html
Ktorý reliéf vlastne máme použitý?

**Comment by zdila** [comment]
@didoa ma tiez nejake know-how

**Comment by zdila** [comment]
A v jednom tahu by sa mohlo poriesit hned aj #54 :-)

**Comment by didoa** [comment]
nemenila sa nejaka kniznica/updade image magick ?

**Comment by zdila** [comment]
@didoa mozno aj ano, kedze pred cca tyzdnom @nickn17 upgradoval cely system.

**Comment by tjamecny** [comment]
pred nejakým časom som s @kaylesk diskutoval o generovaní vrstevníc, tak som predpokladal, že ich už nahral na server. Ak to ale nespravil, tak potom je asi chyba na serveri, ako píše @didoa ...

**Comment by kaylesk** [comment]
Nie ešte som ich nerobil :( a reliéf som len ten skúšobný kúsok teraz zrobil.

**Comment by zdila** [comment]
Kto to prosim vie opravit? A kto to opravi? Alebo je niekde dokumentacia ako sa lepia tie tiles so shadingom? Ak ano, mozem to skusit ja.

**Comment by tjamecny** [comment]
Skript pre skladanie tiles  je v /home/httpd/dev/app/core/disk/prerendering2, a ten volá na riadku 166 CAllInOne, ktorý vykonáva samotné lepenie jednotlivých vrstiev dokopy. Ale či je tam uložená aj konfigurácia pre imagemagick, som nepozeral.

**Comment by zdila** [comment]
Pozeral som tie skripty a nakoniec som sa rozhodol ze sa idem radsej pohrat s mapnikom ;-)

**Comment by didoa** [comment]
od problemu s reliefom sme sa dostali  k mapniku ? ... opat ideme zahodit celu tu krasu freemapu ?  :)
a uz aspon vieme, co sposobuje problem, alebo iba vieme, ze niekde nieco nejde ? :D 

@tjamecny : CAllInOne iba spaja vrstvy podla konfiguracie, jde A, T C su akoby makra, popisujuce ktore vrstvy  v akom poradi polepit, ze by na konci ako mapa vyzeralo.

znovu to sem pisem: asi sa zmenilo ako imagemegick robi operaciu  multiply... (lib/core/allinone.inc.php riadok ~450), pouzivali sme verziu 6, imageMagick web pise, ze maju novu verziu, ktore je by default High Dynamic Range... to moze byt ten rozdiel, @tjamecny mame verziu 7 ?   

```
// convert it  ->> kod ktory spaja obrazky tou "speci metodou"
            exec("convert tmp/ramdisk/src" . $pid . ".png  $Url -compose Multiply -composite  tmp/ramdisk/result" . $pid . ".png");
 
```
este sa mohli zmenit podkladove data pre relief :) 

len tak pre buducich badatelov:  freemap mal podklad pre relef, ktory bol zlozeny z 3 iteracii (imitacia swisstopo style):
- juhozapadne svahy mierne do zlta (slnko) 
- severovychodne svahy  malinko do modra (tien)
- jedna klasicka siva slabucka relefna vrstva, nieco mala speci, neviem si spomenut presne konfig, ale asi ho viem najst vo forme skriptu pre maperitive (@kaylesk ho podla mna ma) - cele taky ten swisstopo style

a ked toto vyriesime, mozem pregenerovat relef, zjavne spravime par iteracii, aby sme vybrali ten,  ktory sa nam paci najviac, a je po probleme :) oki ?

**Comment by zdila** [comment]
> od problemu s reliefom sme sa dostali k mapniku ? ... opat ideme zahodit celu tu krasu freemapu ? :)

@didoa Vystup momentalneho sposobu renderovania je krasny, no ked sa nieco pobabre, tak to vedia fixnut len dvaja ludia, ktori su ale tiez dost vytazeni. A na vyvoj temy je tiez privetivejsie prostredie, ktore ma velku komunitu a dokumentaciu a vysledok uprav si vies velmi rychlo lokalne vyrenderovat a pozriet. Ceresnicka na torte pre mna, ze mapnik ma pribalene API pre nodejs, takze radost integrovat :-).

Ale neboj, ja si mapnikom len chcem odburat svoju frustraciu, naucit sa nieco nove a ak motyka vystreli, tak do par rokov vyrobit alternativu k sucasnej teme ;-).

**Comment by didoa** [comment]
> @didoa Vystup momentalneho sposobu renderovania je krasny, no ked sa nieco pobabre, tak to vedia fixnut len dvaja ludia, ktori su ale tiez dost vytazeni. A na vyvoj temy je tiez privetivejsie prostredie, ktore ma velku komunitu a dokumentaciu a vysledok uprav si vies velmi rychlo lokalne vyrenderovat a pozriet. Ceresnicka na torte pre mna, ze mapnik ma pribalene API pre nodejs, takze radost integrovat :-).
> 
> Ale neboj, ja si mapnikom len chcem odburat svoju frustraciu, naucit sa nieco nove a ak motyka vystreli, tak do par rokov vyrobit alternativu k sucasnej teme ;-).

@zdila  V pohode, vyskusal som aj mapnik/tilemill aj maperitive, maju svoje vyhody aj nevyhody... drzim palce, ak niekto spravi rychejsiu a spolahlivejsiu verziu freemap renderingu... :) verim ze sa to da, lebo vsak aj web vznikol, tak to proste musi ist niekedy a nejako, len si myslim, ze to bude dalsi poriadny kusisko prace

**Comment by kaylesk** [comment]
Vraj sa čosi menilo v spracovaní alfa kanála v imagemagick v7 oproti v6, viď. http://www.imagemagick.org/discourse-server/viewtopic.php?t=33193 (nie úplne identický problém)
Možno ten "+swap"?

**Comment by didoa** [comment]
mozne to je, treba skusit ... :)

**Comment by tjamecny** [comment]
Skript na skladanie tiles bol medzičasom opravený, zatváram issue.
