### ISSUE TITLE
nefunkčné POI gpx requesty

### ISSUE THREAD

**Issue by mlendl** [FreemapSlovakia/FreemapDiSK#81]
zistil som, že sa nefungujú niektoré POI gpx requesty, konkrétne tento - reštaurácie
http://dev.freemap.sk/api/0.1/poi/list?subcategory_id=4&format=gpx

**Comment by tjamecny** [comment]
Tento request vráti dosť veľa dát (>1MB), s čím má problém cachovanie na serveri (SQUID).
Použi tento odkaz: http://dev.freemap.sk:82/api/0.1/poi/list?subcategory_id=4&format=gpx

**Comment by tjamecny** [comment]
Nakoľko nevidíme žiadny prínos v SQUIDe, bol vypnutý a priamo na porte 80 už beží Apache.
To znamená, že treba použiť pôvodný odkaz (bez ":82").
