### ISSUE TITLE
Chybne renderovane/tienovane stvorce na vrstve T Freemap 

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#82]
Chcem nahlasit chybu v T vrstve Freemap
Okolo Velkeho Choca
https://www.freemap.sk/?map=14/49.137324/19.328013&layers=T

Okolo Malina Brda a Lubochnianskej doliny
https://www.freemap.sk/?map=14/49.068299/19.223585&layers=T

Okolo Smrekovice
https://www.freemap.sk/?map=14/48.956500/19.225012&layers=T

Okolo Donovalov a Prasivej
https://www.freemap.sk/?map=15/48.887972/19.284185&layers=T

Zapadne Tatry
https://www.freemap.sk/?map=15/49.189816/19.788118&layers=T

Prosim pozrite sa na to.
Dakujem

**Comment by tjamecny** [comment]
Vďaka za report.
Pozrel som sa narýchlo na to, a minimálne jeden problém je v OSM dátach, lebo les na OSM.org je tiež rozbitý: [https://www.openstreetmap.org/relation/1280934#map=14/48.9017/19.1451](url)
![les_osm](https://user-images.githubusercontent.com/16599347/55573352-12e81580-570a-11e9-90f9-75f22514b622.png)

Hoci ten les je už ako multipolygón, aj tak sa niekto pokúsil v nôm spraviť dieru starým spôsobom (ktorý nefunguje):
![les_diera_zle](https://user-images.githubusercontent.com/16599347/55573373-1b405080-570a-11e9-8632-efa2324c19a0.jpg)

Opravil som to:
![les_diera_oprava](https://user-images.githubusercontent.com/16599347/55573397-24312200-570a-11e9-8449-730d9902a5f3.jpg)

Až zajtra dobehne renderovanie, dám manuálne prerenderovať chýbajúce plochy na mape (ak nejaké ostanú).

Ďalší problém je vo Vysokých Tatrách, napr. https://www.openstreetmap.org/way/100711225 . Na freemap-e nerenderujeme natural=rock. A podľa OSM Wiki https://wiki.openstreetmap.org/wiki/Tag:natural=rock to vyzerá byť zle otagované. Vhodnejšie sa mi zdá https://wiki.openstreetmap.org/wiki/Tag:natural=bare_rock .

Sú tri možnosti:
- ak sa ti to zdá zle otagované, pretaguješ to na natural=bare_rock
- ak si nie si istý, spýtaš sa na mailing liste
- ak si si istý, že natural=rock je správne, tak daj nejaký návrh, ako to renderovať (či stačí nejaká sivá farba, možno ikona, atď.)

**Comment by tjamecny** [comment]
Tak som objavil ďalší problém: zmizli nejaké relácie pre lesy nielen z TRAPI, ale aj z DB, napr.:
https://www.openstreetmap.org/relation/9113779
https://www.openstreetmap.org/relation/9113600
https://www.openstreetmap.org/relation/5982761

Nakoľko chýbajú aj v DB, je nutný kompletný import OSM dát z planet.osm, čo zaberie dosť veľa času (minimálne týždeň).

**Comment by zdila** [comment]
Inac take velke relacie postupne obcasne rozbijam na mensie kusy.

**Comment by tjamecny** [comment]
Tiež mi napadlo, že napríklad popri cestách I/II/III. triedy to rozdeliť. Len treba správne presunúť inner členov do nových relácií a to nie je záležitosť na pár minút. Stačí jedna chybička a zas bude pol Slovenska bez lesa :)

**Comment by zdila** [comment]
Ja zatial delim na uzsich miestach. Ale najprv spajam male kusky do velkych a zlucujem tie plochy z CLC ktore sa lisia len typom lesa. To CLC je take nepresne a lesy uz tak prerobene ze ta info uz nesedi.

Inac momentlne je tych chybnych dlazdic neunosne.

![image](https://user-images.githubusercontent.com/636095/55685866-22aa6880-595b-11e9-9424-d03155e0568a.png)

**Comment by tjamecny** [comment]
> Inac momentlne je tych chybnych dlazdic neunosne.

Už beží reimport dát do DB, a následne aj do TRAPI. Rendering som zablokoval hneď ráno.
Ale stále si neviem vysvetliť, prečo tak hromadne a naraz vypadlo niekoľko relácií :(
Keď v minulosti vypadla nejaká relácia, tak len z TRAPI a bolo ju jednoduché doplniť z DB. Teraz nie sú ani v DB, preto ten reimport dát.

**Comment by aceman444** [comment]
https://www.openstreetmap.org/way/100711225 urcite ma byt bare_rock, idem to opravit.

**Comment by tjamecny** [comment]
Mapa je už OK, zatváram issue.
