### ISSUE TITLE
Garmin mapy Freemap - chybne renderovanie

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#83]
Po dakom case som sa opat rozhodol stiahnut aktualizovane mapy pre Garminu Oregon na stranke http://old.freemap.sk/index.php?c=core.download&filename=/garmin

Problem je, ze namiesto map su tam len vrstevnice a subor ma len okolo 60 MB.

Takyto problem sa uz v minulosti objavil. Zrejme o tom nik nevie, tak ho hlasim.
Prosim pozrite sa na to.
M.

**Comment by kaylesk** [comment]
Dá sa to nahlásiť aj priamo tu https://github.com/FreemapSlovakia/freemapSKtopo/issues
Do minulého týždňa som na to občas hodil očko, lebo sa to presúvalo na iný počítač, takže pekne počkal keď ostal bez dozoru :)
Pustím to znova.
