### ISSUE TITLE
Donau

### ISSUE THREAD

**Issue by dot256** [FreemapSlovakia/FreemapDiSK#84]
https://www.freemap.sk/?map=16/48.143475/17.073913&layers=Tc

**Comment by tjamecny** [comment]
Toto súvisí s #82. Dáta už sú na freemape kompletné, len daná oblasť je veľmi náročná na renderovanie, potrvá ešte deň/dva, kým sa zmena prejaví na mape.
Prikladám náhľad pôvodného podkladu (vľavo) a novo vyrenderovaného (vpravo), chýbalo tam toho viac, ako len Dunaj:
![ba_old_new](https://user-images.githubusercontent.com/16599347/56455001-840a0880-6359-11e9-9a16-8cf50a9a70c8.png)

Vďaka za report. Až bude zmena viditeľná na mape, zavriem issue.

**Comment by tjamecny** [comment]
Mapa je už OK, zatváram issue.
