### ISSUE TITLE
overlay "kto rendruje dlazdice" je vidno v "produkcii"

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/FreemapDiSK#88]
alebo je to len u mna? Mapu je normalne vidno, ale nad nou sa vznasa overlay s menami rendrovacich klientov. Mozem poslat img ak treba.

**Comment by zdila** [comment]
1. reportujes do zleho projktu
2. vypni si tu vtstvu:

![image](https://user-images.githubusercontent.com/636095/60910589-86597000-a281-11e9-8109-65fb9ad13751.png)

**Comment by alexanderzatko** [comment]
aha - hladal som to tam, ale bolo to schovane dolu, mimo viewport. Musel som to omylom zapnut ked som stlacil R.
Ozaj preco je toto zly projekt pre reportovanie tohoto problemu? Poslal ma sem odkaz v tvojej aplikacii. No, nie celkom - sprostredkovane - ale je to matuce ze na http://wiki.freemap.sk/NahlasenieChyby je link na tento projekt. Zmenime to?

**Comment by zdila** [comment]
je mnoho projektov na rozne funkcie - X vrstva, stare vrstvy, web, backend, vyhladavac ciest, vyhladavac podla mena. bezny user tazko trafi kde co reportovat. nemam rychly napad ani kapacitu to riesit.

**Comment by tjamecny** [comment]
> aha - hladal som to tam, ale bolo to schovane dolu, mimo viewport. Musel som to omylom zapnut ked som stlacil R.

Klavesove skratky na novom freemape su super vec, aj ked obcas mozu sposobit taky problem, aky nastal u teba :)

> Ozaj preco je toto zly projekt pre reportovanie tohoto problemu? Poslal ma sem odkaz v tvojej aplikacii. No, nie celkom - sprostredkovane - ale je to matuce ze na http://wiki.freemap.sk/NahlasenieChyby je link na tento projekt. Zmenime to?

Na odkazovanej wiki je napisane "Ak ste našli chybu **na mape**", a to nie je zrovna tento pripad. Vsetko, co sa tyka noveho webu, patri do "freemap-v3-react". Ak sa chyba tyka starej mapy, vtedy to patri do "FreemapDiSK". A ak je nejaky problem s novou outdoorovou mapou, potom treba reportovat do "freemap-mapnik".

Ale suhlasim, ze stranka na Wiki je neaktualna. Ak mas cas a chut, mozes ju upravit, inak to spravim ja cez vikend.

**Comment by alexanderzatko** [comment]
no, bolo by dobre to asi trochu upravit pre "general public", ale mozno to nestoji za namahu, kedze vy dvaja aj tak veci sledujete a teda zmatenych ludi (ako som ja) usmernite ked veci vlozia do nespravneho "chlievika" :-)
...okrem ineho sa zda, ze pomylencov nie je vela aby sa bolo treba namahat
