### ISSUE TITLE
Na zoome 17 a 18 nerenderuje niektore highway=service

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#9]
Na zoome 17 a 18 nerenderuje niektore highway=service, vyzera to, ze napr. service=parking_aisle. Ale na nizsich zoomoch sa renderuju. Ak tam ma byt rozdiel, tak potom asi naopak: renderovat az od zoomov 15 nizsie (do 18), lebo na 12-14 su dost neviditelne a asi nadbytocne.

**Comment by tjamecny** [comment]
Ako je uz spomenute v https://github.com/FreemapSlovakia/FreemapDiSK/issues/3#issuecomment-269807346 ,  zoomy 17 a 18 sa zatial nerenderuju cez DiSK, preto zatvaram.
