### ISSUE TITLE
dunaj v BA nieje rendrovany v sirke koryta

### ISSUE THREAD

**Issue by tomaskovacik** [FreemapSlovakia/FreemapDiSK#90]
v BA na hiking/car/bike mape nieje dunaj vyliaty do celeho koryta. Na OSM aj na X je to ok. Mimo BA je to na vsetkychmapach OK

**Comment by tjamecny** [comment]
Opäť raz zmizla [jedna](http://dev.freemap.sk/trapi/api/0.6/map/relation/2740095) relácia Dunaja z TRAPI(*), pritom [susedná](http://dev.freemap.sk/trapi/api/0.6/map/relation/2740094) je v pohode.
Už si len musím spomenúť, ako som som dopĺňal chýbajúce dáta do TRAPI.

(*) - TRAPI je lokálna kópia OSM dát, ktorá sa používa na renderovanie cez DiSK.

@zdila - vďaka za expresné presunutie tejto Issue na správne miesto :mask:

**Comment by tjamecny** [comment]
Reláciu [2740095](http://dev.freemap.sk/trapi/api/0.6/map/relation/2740095) som doimportoval do TRAPI. Skontrolujem o pár dní, či je problém vyriešený a potom zavriem túto Issue.

Vďaka za report.

**Comment by tjamecny** [comment]
Oprava zabrala, zatváram Issue.
![obrázok](https://user-images.githubusercontent.com/16599347/78705723-31c94b00-790e-11ea-8db3-5cfa3837f2c3.png)
