### ISSUE TITLE
problemy rendrovania v T vrstve

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/FreemapDiSK#91]
Obidva problemy su len na T vrstve:
1. https://www.freemap.sk/?map=13/48.692377/19.745178&layers=T
relacia lesa je 9466792 ale vyzera OK.

2. https://www.freemap.sk/?map=14/48.902446/20.544434&layers=T
v tomto pripade som chybu sposobil ja, pretoze som cast inner polygonu tagoval ako outer, ale aj po oprave je stale vidno v mape chybu.

**Comment by tjamecny** [comment]
V prvom prípade zmizla relácia z TRAPI (http://dev.freemap.sk/trapi/api/0.6/map/relation/9466792), doimportujem ju ručne.
V druhom prípade nevidím žiadny rozdiel medzi T a X vrstvou, čo konkrétne chýba?

**Comment by alexanderzatko** [comment]
Ten druhy problem je vyrieseny - asi cache alebo este neboli dlazdicky prerendrovane ked som pozeral. Dikes :-)

**Comment by tjamecny** [comment]
Skontrolované, vyzerá byť v poriadku, zatváram túto Issue.
![image](https://user-images.githubusercontent.com/16599347/80611639-28c62800-8a3b-11ea-9f0a-863c7824239d.png)
