### ISSUE TITLE
les - rendering problem

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/FreemapDiSK#92]
https://www.freemap.sk/?map=13/49.238841/19.190197&layers=T

Tyka sa to asi tejto relacie:

https://www.openstreetmap.org/relation/9366692

**Comment by tjamecny** [comment]
Áno, presne tá relácia nám vypadla z TRAPI
Doimportoval som ju a aj dal prerenderovať dané územie.
Po skontrolovaní výsledku zavriem túto issue.

Vďaka za report.

**Comment by tjamecny** [comment]
Už je to v poriadku, zatváram.
![image](https://user-images.githubusercontent.com/16599347/83271291-f2123780-a1c9-11ea-8b17-ba9054dd2c79.png)

**Comment by alexanderzatko** [comment]
dikes :-)
