### ISSUE TITLE
Chybná nadmorská výška vrstevníc

### ISSUE THREAD

**Issue by JanGunis** [FreemapSlovakia/FreemapDiSK#93]
Pri obci Kríže (https://www.freemap.sk/?map=17/49.242332/21.149089&layers=XI) sú chybne vyznačené nadmorské výšky vrstevníc. Kríže majú nadmorskú výšku 660 m.n.m a najbližšia vrstevnica má označenie 550. Kríže ležia v doline potoka, takže vrstevnice smerom od potoka (východne aj západne) by mali byť označené väčšou hodnotou.

**Comment by zdila** [comment]
Problem bude skor ze KST zle zameralo nadmorsku vysku razcestnika. Treba pisat im. Naviac to hlasite do zleho porjektu.
