### ISSUE TITLE
DiSK nefunguje s Inkscape 1.0

### ISSUE THREAD

**Issue by aceman444** [FreemapSlovakia/FreemapDiSK#95]
DiSK zamietne novy Inkscape 1.0 (vydany 1.5.2020), pretoze ma chybnu kontrolu verzie Inkscape.
Okrem toho ma Inkscape 1.0 zmenene parametre na export do suboru oproti povodnemu 0.9x.

Mam to vyriesene, nahram pull request.

**Comment by aceman444** [comment]
Hotovo, zmeny v 3 suboroch.

**Comment by tjamecny** [comment]
Vďaka za opravu, vyskúšam to s verziou Inkscape 0.92.4, ktorá je v Debian stable.

**Comment by aceman444** [comment]
Ano, dakujem, treba overit, ci som nerozbil 0.9x :)

**Comment by tjamecny** [comment]
Spätná kompatibilita je dodržaná, merge-ol som.
Ešte raz vďaka.

**Comment by aceman444** [comment]
Super, dakujem.
