### ISSUE TITLE
Nerenderuju sa nove objekty na Freemap

### ISSUE THREAD

**Issue by Mirecnet** [FreemapSlovakia/FreemapDiSK#99]
Vcera som si vsimol, ze sa nerenderuju nove objekty na Freemap.

OSM - chodnik v Klinoch 
https://www.freemap.sk/#map=19/49.206553/19.624258&layers=O

Freemap
https://www.freemap.sk/#map=19/49.206553/19.624258&layers=X

Neviem, ci o tom viete, tak hlasim. Pozrite sa na to prosim.

**Comment by zdila** [comment]
viem o tom, bezia tam teraz ine procesy
